# Generated by Django 5.1.3 on 2024-12-25 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
                ('state_flower', models.CharField(max_length=100)),
                ('capital_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county_seat', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='app.state')),
            ],
        ),
    ]
